# Generated by Django 3.0.8 on 2020-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_url',
            field=models.CharField(max_length=26000),
        ),
    ]
